### ISSUE TITLE
[Create first cmd] Delete a moderator role problems

### ISSUE THREAD

**Issue by Tuddual** [Tuddual/tudbot#7]
For #2 

If a role was assigned as moderator and after deleted.
!setmoderators still list it.

- [x] need to fetch roles
- [x] delete the role if it doesn't exist anymore

**Comment by Giotje** [comment]
Hey! is it oke if i pick this issue up?

**Comment by Tuddual** [comment]
Yea sure !

**Comment by Giotje** [comment]
oke so after taking a dive there are a lot of bugs i want to give you some feedback:

- If you open source a project, please use [dockblocks](https://devdocs.magento.com/guides/v2.4/coding-standards/docblock-standard-javascript.html) 
- The way the fetched roles is with text formatting aswell. i iterated over the roles i was fetching expecting a match but i wasn't getting one because of the way you save the role id's

I can't help you with this issue until the second comment is fixed.

If you need my help (I work as a full-time javascript software engineer) you can tell me. but I don't have enough time (right now) to fix these bugs i found

**Comment by Tuddual** [comment]
Thank you for the feedback @Giotje !

I am kinda new at programming Javascript but I tried to code correctly with using eslint for example.
I didn't know about the JavaScript DocBlock standard but I'll try to use it in the future.

I understand that the way I used to save roles isn't really good, I will use just role number without <@&...> in the future.

**Comment by Giotje** [comment]
Hey, @Tuddual 

no problem! 

i didn't have enough time to fix the bugs, but I will continue on this issue right now. i don't know if you've re-written anything.

also trying keeping the master branch up-to date with all your new (stable) code.

will update this issue with a new pull request!

**Comment by Tuddual** [comment]
Hey @Giotje !

I work a little bit and tried to fix the issues with [8037328](https://github.com/Tuddual/tudbot/commit/8037328e3da41f021915372766d96cf1b8b1f361) and [7bf79f7](https://github.com/Tuddual/tudbot/pull/9/commits/7bf79f7eeae64ede5c3c397b40d28c7aae218892).

The issue has been transformed over an other issue that I have with the async/await.
The role is deleted as wanted, but the next part of the programm run before the deletion (evenif I added the asynch/await).

**Comment by Giotje** [comment]
Great job on figuring this out :rocket:. if you need any more help lemme know! i was busy with holidays and gf/family things.
